# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write 

jobs:
  build:

    runs-on: windows-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup .NET (adjust version if needed)
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # 3. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # 4. Build & Publish as self-contained exe
      - name: Build exe
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true --no-restore

      # 5. Upload exe as an artifact
      - name: Upload exe
        uses: actions/upload-artifact@v4
        with:
          name: Tempo.Exporter
          path: |
            **/publish/*
      
      # 5. Zip the artifacts
      - name: Zip artifacts
        run: |
          Compress-Archive -Path publish/* -DestinationPath Tempo.Exporter.zip

      # 6. Create a release with the artifacts attached
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "Release ${{ github.run_number }}"
          files: Tempo.Exporter.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
